### ISSUE TITLE
Settings crash when UserCard image was set.

### ISSUE THREAD

**Issue by xjl12** [Octavi-OS/platform_packages_apps_Settings#69]
When I have chosen a photo from Google Photo to set my UserCard image, each time I open Settings, it crashed. The logcat I catched as followed:
```
03-05 19:54:51.827  3560  3560 E AndroidRuntime: java.lang.SecurityException: Permission Denial: reading com.google.android.apps.photos.contentprovider.impl.MediaContentProvider uri content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F18/ORIGINAL/NONE/image%2Fjpeg/1827521385 from pid=3560, uid=1000 requires the provider be exported, or grantUriPermission()
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2409)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2392)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2029)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1844)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1520)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at com.android.settings.deviceinfo.UserInfoFragement.onUserCard(UserInfoFragement.java:150)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at com.android.settings.deviceinfo.UserInfoFragement.onStart(UserInfoFragement.java:82)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performStart(Fragment.java:3011)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:565)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:276)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1667)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3234)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3185)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:262)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:482)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1468)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:8075)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3661)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2211)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7837)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
03-05 19:54:51.827  3560  3560 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
It looks like a permission problem.

**Comment by delianjekov** [comment]
Any updates? Any way to remove the avatar to avoid the issue?
